bind_addr = ":8081"
log_level = "debug"

[store]
database_url = "sqlserver://sa:123@localhost:51000?database=restapi_dev&connection+timeout=30"
# database_url = "host=localhost dbname=restapi_dev sslmode=disable"