bind_addr = ":8080"
log_level = "debug"

[store]

# database_url = "host=localhost dbname=restapi_dev sslmode=disable"
database_url = "sqlserver://sa:123@localhost?database=restapi_dev&connection+timeout=30"