bind_addr = ":8080"
log_level = "debug"
# database_url = "sqlserver://sa:123@localhost:51000?database=restapi_dev&connection+timeout=30"
database_url = "host=localhost user=postgres password=123 dbname=restapi_test sslmode=disable"